# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 7.9.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
#after_script:
#  - git config user.name "vaniot-s"
#  - git config user.email "vaniot@yeah.net"
#  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
#  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
#  - cat ./_config.yml
#  - hexo deploy
# End: Build LifeCycle
#
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
#  keep-history: true
#  on:
#    branch: master
after_script:
  - cd ./public
  - git init
  - git config user.name "vaniot-s"   #修改成自己的github用户名
  - git config user.email "vaniot@yeah.net"   #修改成自己的GitHub邮箱
  - git add .
  - git commit -m "update by Travis-CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_token就是在travis中设置的token

#branches:
#  only:
#    - hexo  #只监测这个分支，一有动静就开始构建
env:
  global:
    - GH_REF: github.com/vaniot-s/vaniot-s.github.io

