# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Vaniot
subtitle: blog
description: up up up
author: Vaniot
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://vaniot-s.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
material_dir: materials
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
        web: web
        基础: basic
        工具: tool
        应用: application
        资料: material
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true # Doesn't escape HTML content so the tags will appear as html.
    xhtmlOut: false # Parser will not produce XHTML compliant code.
    breaks: true # Parser produces `<br>` tags every time there is a line break in the source document.
    linkify: false # Returns text links as text.
    typographer: true # Substitution of common typographical elements will take place.
    quotes: '“”‘’' # "double" will be turned into “single”
                   # 'single' will be turned into ‘single’
  plugins:
     - markdown-it-abbr
     - name: markdown-it-container
       options: success
     - name: markdown-it-container
       options: info
     - name: markdown-it-container
       options: warning
     - name: markdown-it-container
       options: danger
     - markdown-it-deflist
     - name: markdown-it-emoji
       options:
         shortcuts: {}
     - markdown-it-footnote
     - markdown-it-imsize
     - markdown-it-ins
     - markdown-it-mark
     - markdown-it-regexp
     - markdown-it-sub
     - markdown-it-sup
     - markdown-it-checkbox
  anchors:
       level: 1, 2 # Minimum level for ID creation. (Ex. h2 to h6)
       collisionSuffix: 'v' # A suffix that is prepended to the number given if the ID is repeated.
       permalink: true # If true, creates an anchor tag with a permalink besides the heading.
       permalinkClass: header-anchor # Class used for the permalink anchor tag.
       permalinkSymbol: '' # The symbol used to make the permalink.

#math
math:
    engine: 'mathjax'
    mathjax:
        src: "//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
        config:
            tex2jax:
                inlineMath: [ ['$','$'], ["\\(","\\)"] ]
#sequence
sequence:
    webfont: "//cdnjs.cloudflare.com/ajax/libs/webfont/1.6.27/webfontloader.js"
    snap: "//cdnjs.cloudflare.com/ajax/libs/snap.svg/0.4.1/snap.svg-min.js"
    underscore: "//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"
    sequence: "//cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js"
    style: ""
    options: 
       theme: simple
       css_class: ""
     
#flowchart:
flowchart:
    raphael: "//cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"
    flowchart: "//cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js"
    options: 
       scale: 1,
       line-width: 2
       line-length: 50
       text-margin: 10
       font-size: 12
# plugins:
#     - hexo-reference
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-hiker

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#deploy:
#  type: git
#  repository: git@github.com:Vaniot-s/vaniot-s.github.io.git
#  branch: master

# use travis deploy
deploy:
  - type: git
    # 下方的gh_token会被.travis.yml中sed命令替换
    repo: https://gh_token@github.com/xiong-it/xiong-it.github.io.git
    branch: master

